# Generated by Django 4.2.4 on 2023-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0002_news_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
        migrations.AddField(
            model_name='news',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pozycja 1 (Największa)'), (2, 'Pozycja 2'), (3, 'Pozycja 3')], null=True),
        ),
    ]
