# Generated by Django 4.2.4 on 2023-09-19 10:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0007_newestcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newestcourse',
            name='link',
        ),
        migrations.AddField(
            model_name='newestcourse',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newestcourse',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
