# Generated by Django 4.2.4 on 2023-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0008_remove_newestcourse_link_newestcourse_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newestcourse',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
