# Generated by Django 4.2.4 on 2023-09-19 15:52

import backend1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0010_hashtag_article_hashtags_cryptoanalysis_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='hashtags',
            field=models.ManyToManyField(default=backend1.models.python_default, to='backend1.hashtag'),
        ),
        migrations.AddField(
            model_name='newestcourse',
            name='hashtags',
            field=models.ManyToManyField(default=backend1.models.python_default, to='backend1.hashtag'),
        ),
        migrations.AddField(
            model_name='news',
            name='hashtags',
            field=models.ManyToManyField(default=backend1.models.python_default, to='backend1.hashtag'),
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='hashtags',
            field=models.ManyToManyField(default=backend1.models.python_default, to='backend1.hashtag'),
        ),
    ]
