# Generated by Django 4.2.4 on 2023-09-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0011_editorial_hashtags_newestcourse_hashtags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
