# Generated by Django 4.2.4 on 2023-09-19 21:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0012_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoanalysis',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
